[webservers]
web-1 ansible_host=51.250.107.57 fqdn=web-1.ru-central1.internal
web-2 ansible_host=51.250.107.58 fqdn=web-2.ru-central1.internal

[databases]
db-main ansible_host=51.250.107.45 fqdn=fhmo6vdcl437a0oojg8t.auto.internal
db-replica ansible_host=51.250.107.67 fqdn=fhmvjpo381k68jkmp96t.auto.internal

[storage]
storage ansible_host=51.250.107.70 fqdn=storage.ru-central1.internal